# ????????????????
# ???36??????36??????????/????
# ???? 1-16
pageMultiplier: 1

# ??AE?????????? wait/notify ????????????????
craftingPauseThreshold: 100000

# ??????????????????
# ???????????????????????
wirelessMaxRange: 256.0

# ????????????????
# ?????????????????????????
wirelessCrossDimEnable: true

# ?????????????????
# ?????????????????????????????????????????????
# ????????????????????????
providerRoundRobinEnable: true

# ??????????????0 ??????
# ????????????????????????????????
# ???????????????
smartScalingMaxMultiplier: 0

# ??????????
# ??????? HoverText ??????????
showEncoderPatternPlayer: true

# ????????????
# ???????SlotsRow???????????????
patternTerminalShowSlotsDefault: true

# ????????????
entityTickerCost: 512

# ?????????FE?????Applied Flux????????
# ??????????????FE?????????AE??????
prioritizeDiskEnergy: true

# ??????????????????????????/??????minecraft:*?
# ?????????/???????? 'minecraft:chest'?'minecraft:*'?'modid:.*_fluid'
entityTickerBlackList:

# ????????????????????????? 'modid:blockid multiplier'??? 'minecraft:chest 2x'
# ?????/??????? 'minecraft:* 2x' ????????????
entityTickerMultipliers:

